name: Deploy to Firebase Hosting (Live)

on:
  push:
    branches:
      - main # Deploy when code is pushed to the main branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 1. Setup Node Environment (Required for React)
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Recommended Node.js version

      # 2. Install Dependencies
      - name: Install dependencies
        run: npm install

      # 3. Build the LetEX React App (npm run build)
      - name: Build the App
        run: npm run build

      # 4. Deploy to Firebase Hosting
      - name: Deploy to Live Channel
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_LETEX_BROWSER }} # YOUR SECRET NAME HERE
          projectId: letex-39993
          channelId: live
          
